-   id: reorder-python-imports
    name: Reorder python imports
    description: This hook reorders imports in python files.
    entry: reorder-python-imports
    language: python
    types_or: [python, pyi]
    # for backward compatibility
    files: ''
    types: []
    minimum_pre_commit_version: 2.9.2
